// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SOSTouriste.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SOSTouriste.Resources.LanguageResources", typeof(LanguageResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        internal static string menuTitle {
            get {
                return ResourceManager.GetString("menuTitle", resourceCulture);
            }
        }
        
        internal static string accueil {
            get {
                return ResourceManager.GetString("accueil", resourceCulture);
            }
        }
        
        internal static string samu {
            get {
                return ResourceManager.GetString("samu", resourceCulture);
            }
        }
        
        internal static string fireman {
            get {
                return ResourceManager.GetString("fireman", resourceCulture);
            }
        }
        
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        internal static string hospital {
            get {
                return ResourceManager.GetString("hospital", resourceCulture);
            }
        }
        
        internal static string police {
            get {
                return ResourceManager.GetString("police", resourceCulture);
            }
        }
        
        internal static string emergency {
            get {
                return ResourceManager.GetString("emergency", resourceCulture);
            }
        }
        
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        internal static string localisation {
            get {
                return ResourceManager.GetString("localisation", resourceCulture);
            }
        }
        
        internal static string advice {
            get {
                return ResourceManager.GetString("advice", resourceCulture);
            }
        }
        
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        internal static string callEmergency {
            get {
                return ResourceManager.GetString("callEmergency", resourceCulture);
            }
        }
        
        internal static string title_activity_advice {
            get {
                return ResourceManager.GetString("title_activity_advice", resourceCulture);
            }
        }
        
        internal static string title_activity_emergency {
            get {
                return ResourceManager.GetString("title_activity_emergency", resourceCulture);
            }
        }
        
        internal static string title_activity_contact {
            get {
                return ResourceManager.GetString("title_activity_contact", resourceCulture);
            }
        }
        
        internal static string title_activity_profile {
            get {
                return ResourceManager.GetString("title_activity_profile", resourceCulture);
            }
        }
        
        internal static string title_activity_localisation {
            get {
                return ResourceManager.GetString("title_activity_localisation", resourceCulture);
            }
        }
        
        internal static string title_activity_language {
            get {
                return ResourceManager.GetString("title_activity_language", resourceCulture);
            }
        }
        
        internal static string title_activity_help {
            get {
                return ResourceManager.GetString("title_activity_help", resourceCulture);
            }
        }
        
        internal static string title_activity_language_first_time {
            get {
                return ResourceManager.GetString("title_activity_language_first_time", resourceCulture);
            }
        }
        
        internal static string title_activity_test {
            get {
                return ResourceManager.GetString("title_activity_test", resourceCulture);
            }
        }
        
        internal static string title_activity_list {
            get {
                return ResourceManager.GetString("title_activity_list", resourceCulture);
            }
        }
        
        internal static string title_activity_reader {
            get {
                return ResourceManager.GetString("title_activity_reader", resourceCulture);
            }
        }
        
        internal static string action_settings {
            get {
                return ResourceManager.GetString("action_settings", resourceCulture);
            }
        }
        
        internal static string navigation_drawer_open {
            get {
                return ResourceManager.GetString("navigation_drawer_open", resourceCulture);
            }
        }
        
        internal static string navigation_drawer_close {
            get {
                return ResourceManager.GetString("navigation_drawer_close", resourceCulture);
            }
        }
        
        internal static string nameTextView {
            get {
                return ResourceManager.GetString("nameTextView", resourceCulture);
            }
        }
        
        internal static string firstnameTextView {
            get {
                return ResourceManager.GetString("firstnameTextView", resourceCulture);
            }
        }
        
        internal static string locateConsulate {
            get {
                return ResourceManager.GetString("locateConsulate", resourceCulture);
            }
        }
        
        internal static string locatePolice {
            get {
                return ResourceManager.GetString("locatePolice", resourceCulture);
            }
        }
        
        internal static string consulate {
            get {
                return ResourceManager.GetString("consulate", resourceCulture);
            }
        }
        
        internal static string policeStation {
            get {
                return ResourceManager.GetString("policeStation", resourceCulture);
            }
        }
        
        internal static string mapsInstallText {
            get {
                return ResourceManager.GetString("mapsInstallText", resourceCulture);
            }
        }
        
        internal static string problemFile {
            get {
                return ResourceManager.GetString("problemFile", resourceCulture);
            }
        }
        
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        internal static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        internal static string blood {
            get {
                return ResourceManager.GetString("blood", resourceCulture);
            }
        }
        
        internal static string remarks {
            get {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }
        
        internal static string adviceList {
            get {
                return ResourceManager.GetString("adviceList", resourceCulture);
            }
        }
        
        internal static string firstTime {
            get {
                return ResourceManager.GetString("firstTime", resourceCulture);
            }
        }
        
        internal static string askLocationTitle {
            get {
                return ResourceManager.GetString("askLocationTitle", resourceCulture);
            }
        }
        
        internal static string askLocationText {
            get {
                return ResourceManager.GetString("askLocationText", resourceCulture);
            }
        }
        
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        internal static string helpText {
            get {
                return ResourceManager.GetString("helpText", resourceCulture);
            }
        }
        
        internal static string adviceLabel {
            get {
                return ResourceManager.GetString("adviceLabel", resourceCulture);
            }
        }
        
        internal static string queryConsulate {
            get {
                return ResourceManager.GetString("queryConsulate", resourceCulture);
            }
        }
        
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        internal static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }
        
        internal static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        internal static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        internal static string italian {
            get {
                return ResourceManager.GetString("italian", resourceCulture);
            }
        }
        
        internal static string netherlands {
            get {
                return ResourceManager.GetString("netherlands", resourceCulture);
            }
        }
        
        internal static string polish {
            get {
                return ResourceManager.GetString("polish", resourceCulture);
            }
        }
        
        internal static string portuguese {
            get {
                return ResourceManager.GetString("portuguese", resourceCulture);
            }
        }
        
        internal static string queryPolice {
            get {
                return ResourceManager.GetString("queryPolice", resourceCulture);
            }
        }
        
        internal static string queryHospital {
            get {
                return ResourceManager.GetString("queryHospital", resourceCulture);
            }
        }
    }
}
